### ISSUE TITLE
As a brand.uiowa.edu maintainer, I can use components from UIDS

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#110]
- [ ] Font Awesome refactor https://github.com/uiowa/uids/issues/111
- [ ] Create A-Z list component #109  
- [ ] Refactor hero block #108 (#107)
- [ ] Refactor alerts component #106 
- [ ] Refactor card component #104 
- [ ] CSS Grid Mixin #102 
- [ ] Provide static version of header #92 
- [x] Create alert component: https://github.com/uiowa/uids/issues/81 @bspeare
