### ISSUE TITLE
Additional events component updates 

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#120]
# Tasks

- [ ] Events svg Font awesome icon centered (@bspeare)
- [ ] Add time to events date (@bspeare)
- [ ] Add padding to `last-child` event row (@bspeare)
