### ISSUE TITLE
UIDS Updates for layout builder feature maturity

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#300]
Minor style updates for layout builder feature maturity (https://github.com/uiowa/uiowa/issues/1778)

- [x] https://github.com/uiowa/uids/issues/299 Lighten brain pattern black background
- [x] https://github.com/uiowa/uids/issues/298 Adjust spacing under bold--underline heading
- [x] https://github.com/uiowa/uids/issues/296 Adjust padding on card without image
- [x] https://github.com/uiowa/uids/issues/287 Increase margin for basic page feature images
- [x] https://github.com/uiowa/uids/issues/274 CTA alignment fix
- [ ] https://github.com/uiowa/uids/issues/275 Pre footer region styles
- [x] https://github.com/uiowa/uids/issues/289 Horizontal rule style
- [x] Integrate stats horizontal variant
- [x] https://github.com/uiowa/uids/issues/224 Hero refactor
