### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#50]
- [ ]  Incorporate all Superfish styles

- [ ]  Add document blocks where necessary (https://github.com/uiowa/uids/blob/master/components/01%20-%20elements/links/link.twig)
- [ ] Refactor folder structure for more atomic - collection/organism
- [x]  Remove logo tab as soon as container breakpoint hits
- [x] Trim down 'Welcome Home' hero image grid text.  Remove subheading and make heading black/gold
- [x] Remove extra space under feature stories
