### ISSUE TITLE
As a site owner, I can use a few different responsive table solutions for my table data

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#507]
As a site owner, I can use a few different responsive table solutions for my table data so that I can choose a solution that works best for mobile. 

It is suggested that the current options for table classes be evaluated at each step of this process.

1. Set default styling with tables, no classes necessary. Also add new utility classes for text alignment.
    - [x] https://github.com/uiowa/uids/issues/509
    - [x] https://github.com/uiowa/uids/issues/508
2. Communicate to users that responsive behavior is changing to different options available. 
    - [x] https://github.com/uiowa/uiowa/issues/3333
3. Set a basic overflow solution for tables by default and remove responsive tables for now: https://codepen.io/bspeare/pen/YzNZbEW. 
    - [x] https://github.com/uiowa/uids/issues/510 
4. Remove `table--static` and `table--is-striped` class from text areas
    - [x] https://github.com/uiowa/uiowa/issues/3330
5. Docs for what is necessary to have good responsive tables 
    - [x] https://github.com/uiowa/uids/issues/513
6. Modify the fixed header solution that users can opt-in: https://codepen.io/bspeare/pen/oNBZRwX.
    - [x] https://github.com/uiowa/uids/issues/512
7. Create a stacked mobile solution that users can opt-in: https://codepen.io/bspeare/pen/XWpMQLP
    - [x] https://github.com/uiowa/uids/issues/514
8.  Add accessibility processing to wysiwyg during content entry instead of through JS so it is saved in the DB.
    - [ ] https://github.com/uiowa/uiowa/issues/3332
## Additional technical/implementation notes
- [ ] Load a lightweight JS that asynchronously loads the heavier JS?

**Comment by bspeare** [comment]
We might want to tackle https://github.com/uiowa/uids/issues/508 as part of the first item in the list.

**Comment by bspeare** [comment]
Since browsers opened up support for `position: sticky` within tables this past June, the direction of this epic changed and I think the work done in https://github.com/uiowa/uids/pull/584 is sufficient to close this epic.
