### ISSUE TITLE
Investigate new Git workflow in UIDS

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#621]
As a developer, I can work within UIDS with a Git workflow similar to the dev and main branches used in https://github.com/uiowa/vuejs-site-template.

# Proposed solution(s)
- [ ] Investigate git workflow and suggest a proposed solution for moving UIDS to this git workflow
- [ ] Implement new git workflow
- [ ] Create 3.x branch and 4.x branch for development instead of working on the main branch in UIDS

**Comment by pyrello** [comment]
Here is a possible way to implement 2 versions of UIDS in UIDS Base: https://reactgo.com/npm-install-same-package-multiple-versions/

**Comment by pyrello** [comment]
This is done.
