### ISSUE TITLE
As a maintainer of UIDS, I can work with a system that is minimally redundant and easy to maintain

### ISSUE THREAD

**Issue by pyrello** [uiowa/uids#79]
- [ ] Determine which components need document blocks #82
- [ ] Investigate refactoring folder structure #83
- [ ] Identify similar templates
- [ ] Create "abstract" templates for common objects (cards, hero blocks, etc.)
- [ ] Implement (via extend or embed) the abstract templates in purpose-specific templates
- [ ] Implement singular templates for items that are currently implemented as collections of items (blocked by #83)
- [ ] Investigate methods for delivering component-level compiled CSS  https://github.com/uiowa/uids/issues/85
- [ ] Investigate methods to present UIDS documentation https://github.com/uiowa/uids/issues/86
- [ ] Investigate method to attach component JS to Fractal's preview build #87

**Comment by pyrello** [comment]
3.x branch is done so closing this. This appears to be related to 3.x
