### ISSUE TITLE
4.x - Move 4.x branch to replace 3.x at uids.brand.uiowa.edu

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#892]
As a campus developer, I can visit uids.brand.uiowa.edu and see an updated version of UIDS4 using Storybook and Vue.js

# Proposed Solution

```[tasklist]
### Tasks
- [x] Update build process to move 4.x branch to replace 3.x at uids.brand.uiowa.edu
- [x] Move 3.x branch so that is available at an archived directory
- [x] Hide unfinished components in 4.x
- [x] Build pages in 4.x branch to link to 3.x branch components that aren't finished in 4.x yet
- [x] Update links on brand.uiowa.edu to UIDS header and footer
- [x] Manually clean up gh-pages
```

**Comment by joewhitsitt** [comment]
Just recently, I know folks have been referencing the header and footer "components". Do we need to stub these out as well?

https://brand.uiowa.edu/applying-brand/web

**Comment by briand44** [comment]
Grooming conversation... Do minimum, stubs for things not transitioned and link to v3. Easy components to transfer likely address in a follow up.

**Comment by GaryRidgway** [comment]
- Change v4 to be the main design system branch, and put v3 on a feature branch that will be accessed at uids.brand.uiowa.edu/v3
- Create stubs for 4x for components that we don't have components for in 4x.
- Link those stubs to the 3x versions of the components.

**Comment by briand44** [comment]
Discussed having a separate slice for stubbing out components that haven't transitioned to 4.x yet and tackle that prior to this slice.

**Comment by briand44** [comment]
Grooming conversation... Possibly a slice of hiding components in 3.x that we don't plan on migrating. Can't remove because still in use by uids_base. What does hiding entail? Removing documentation, remove/make inaccessible to fractal build process but leave css/scss.

Remove or make inaccessible to fractal build documentation files or components that we want to hide. We need to start by figuring out what the list is.

size - small to medium

**Comment by bspeare** [comment]
Update GitHub actions build process for 3.x and 4.x.

**Comment by e-marie-w** [comment]
Yesterday, we updated the build process, so uids.brand.uiowa.edu now reflects the 4.x branch. By clicking on a Not Implemented component, users can get to the 3.x components still. Knowing that, do we still need to create uids.brand.uiowa.edu/v3? Or is that what's meant by the `Move 3.x branch so that is available at an archived directory` step?

The 4.x release was successful, but the gh-pages branch now has loose files that were not there previously. I think they are files from 4.x folders that are not on gh-pages. So my next step is figuring out how to create those folders/make sure future releases put the content into the right folders. Also, if 4.x is the base of uids.brand, I could also remove the /latest directory, correct?

Update: I better understand what's happening now, what was getting dumped into the latest folder is now just getting dumped to the base, so what happened is actually what's expected.

**Comment by e-marie-w** [comment]
Took 5 PRs but 4.x is the default on the site now, with the 3.x stuff going into the `/3.x` directory now. We also manually cleaned up the gh-pages branch. 

It looks like https://uids.brand.uiowa.edu/?path=/story/basic-headline--highlighted-single-word was broken by this works somehow.

Also, the `/assets` folder contains some files that seem to be regenerated with every build. Down the road we should probably add code to clean up old versions of the files.

**Comment by e-marie-w** [comment]
> It looks like https://uids.brand.uiowa.edu/?path=/story/basic-headline--highlighted-single-word was broken by this works somehow.

Looks like we have a fix for this in #759 so I am closing this as done.
