### ISSUE TITLE
Implement day/month design into card component

### ISSUE THREAD

**Issue by bspeare** [uiowa/uids#934]
As it looks in https://github.com/uiowa/uiowa/issues/2727#issuecomment-834403434, implement the day/month design into the card component. 

![117458545-06999c80-af10-11eb-9c1e-e3e6afeda6b6](https://github.com/uiowa/uids/assets/1036433/6324d921-fe46-4de4-a3bc-179c386f9cc3)

```[tasklist]
### Tasks
- [ ] Use the media slot?
- [ ] Create story showing how the design adapts to all variants
- [ ] Grab calendar day/month styles from https://github.com/uiowa/uiowa/blob/a8c39d4939dad7a33d451fba00bf18725b9e1e0a/docroot/sites/registrar.uiowa.edu/modules/registrar_core/css/academic_calendar.css#L101 to start with
```

**Comment by briand44** [comment]
Grooming conversation... The media slot has been used for things like icons, images, etc. Discussion around brand recommended date formats and including that here.

**Comment by GaryRidgway** [comment]
[For ease of use, here is the local storybook link to a version of the card that is horizontal for this.](https://uids.brand.uiowa.edu/?path=/story/components-card--grid&args=orientation:left;media_size:small;media_shape:circle;grid_type:onecol;record_count:1)
